I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/evts_generaux/rien.rpy", line 77, in script
    with Dissolve(.5)
  File "game/screens.rpy", line 1548, in execute
    screen valeurs_traits():
  File "game/screens.rpy", line 1548, in execute
    screen valeurs_traits():
  File "game/screens.rpy", line 1567, in execute
    frame:
  File "game/screens.rpy", line 1569, in execute
    vbox:
  File "game/screens.rpy", line 1572, in execute
    if interfaceMode_ == 0: # résumé, portrait, nom...
  File "game/screens.rpy", line 1597, in execute
    add "[strAffichagePortraitPere]"
Exception: DynamicImage u'[strAffichagePortraitPere]': could not find image. ('images/coteries/conquistadors/portraits/portrait_50+_b.jpg.jpg')

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/evts_generaux/rien.rpy", line 77, in script
    with Dissolve(.5)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 1389, in execute
    renpy.exports.with_statement(trans, paired)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\exports.py", line 1601, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 2251, in do_with
    clear=clear)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 2702, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 3094, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 541, in visit_all
    d.visit_all(callback, seen)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\screen.py", line 430, in visit_all
    callback(self)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\core.py", line 3094, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\screen.py", line 440, in per_interact
    self.update()
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\screen.py", line 625, in update
    self.screen.function(**self.scope)
  File "game/screens.rpy", line 1548, in execute
    screen valeurs_traits():
  File "game/screens.rpy", line 1548, in execute
    screen valeurs_traits():
  File "game/screens.rpy", line 1567, in execute
    frame:
  File "game/screens.rpy", line 1569, in execute
    vbox:
  File "game/screens.rpy", line 1572, in execute
    if interfaceMode_ == 0: # résumé, portrait, nom...
  File "game/screens.rpy", line 1597, in execute
    add "[strAffichagePortraitPere]"
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\sl2\sldisplayables.py", line 430, in sl2add
    d = renpy.easy.displayable(d, scope=scope)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\easy.py", line 110, in displayable
    return renpy.display.image.DynamicImage(d, scope=scope)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\image.py", line 570, in __init__
    self.find_target(scope)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\display\image.py", line 651, in find_target
    raise Exception(error)
Exception: DynamicImage u'[strAffichagePortraitPere]': could not find image. ('images/coteries/conquistadors/portraits/portrait_50+_b.jpg.jpg')

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Fri Mar 26 23:42:18 2021
