I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/extremis/coteries/conquistadors/evts_RejConquistadors.rpy", line 36, in script
    $ coterieConquistadors.RejoindreCoterie(situation_)
  File "game/extremis/coteries/conquistadors/evts_RejConquistadors.rpy", line 36, in <module>
    $ coterieConquistadors.RejoindreCoterie(situation_)
NameError: global name 'pnj' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/extremis/coteries/conquistadors/evts_RejConquistadors.rpy", line 36, in script
    $ coterieConquistadors.RejoindreCoterie(situation_)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/extremis/coteries/conquistadors/evts_RejConquistadors.rpy", line 36, in <module>
    $ coterieConquistadors.RejoindreCoterie(situation_)
  File "extremis/coteries/coterie.py", line 173, in RejoindreCoterie
NameError: global name 'pnj' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Wed Apr 14 20:54:12 2021
