I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/generationUnivers.rpy", line 1, in script
    init -2 python:
  File "game/generationUnivers.rpy", line 3, in <module>
    from despin.abs import situation
ImportError: cannot import name situation

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/generationUnivers.rpy", line 1, in script
    init -2 python:
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/generationUnivers.rpy", line 3, in <module>
    from despin.abs import situation
ImportError: cannot import name situation

Windows-8-6.2.9200
Ren'Py 7.3.5.606
 
Mon Nov 30 20:41:26 2020
