I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/extremis/coteries/templiers/evts_RejTempliers.rpy", line 144, in script
    $ coterieTempliers = coteries_[templiers.Templiers.NOM]
  File "game/extremis/coteries/templiers/evts_RejTempliers.rpy", line 144, in <module>
    $ coterieTempliers = coteries_[templiers.Templiers.NOM]
AttributeError: CollectionCoteries instance has no attribute 'CreerCoterie'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/extremis/coteries/templiers/evts_RejTempliers.rpy", line 144, in script
    $ coterieTempliers = coteries_[templiers.Templiers.NOM]
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/extremis/coteries/templiers/evts_RejTempliers.rpy", line 144, in <module>
    $ coterieTempliers = coteries_[templiers.Templiers.NOM]
  File "extremis/coteries/collection_coteries.py", line 41, in __getitem__
AttributeError: CollectionCoteries instance has no attribute 'CreerCoterie'

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Thu Mar 04 20:03:52 2021
