I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/evts_vie_courante/conduiteVehicule.rpy", line 39, in script
    $ affPilotageExpert = situation_.AffichagePourcentageReussite(trait.Pilotage.NOM, diffRepriseControle6)
  File "game/evts_vie_courante/conduiteVehicule.rpy", line 39, in <module>
    $ affPilotageExpert = situation_.AffichagePourcentageReussite(trait.Pilotage.NOM, diffRepriseControle6)
NameError: name 'diffRepriseControle6' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/evts_vie_courante/conduiteVehicule.rpy", line 39, in script
    $ affPilotageExpert = situation_.AffichagePourcentageReussite(trait.Pilotage.NOM, diffRepriseControle6)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Dev\Renpy\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/evts_vie_courante/conduiteVehicule.rpy", line 39, in <module>
    $ affPilotageExpert = situation_.AffichagePourcentageReussite(trait.Pilotage.NOM, diffRepriseControle6)
NameError: name 'diffRepriseControle6' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
DestinExtremis 1.0
Wed Jan 13 22:27:27 2021
