I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/extremis/coteries/orks/evts_RejOrks.rpy", line 77, in script
    python:
  File "game/extremis/coteries/orks/evts_RejOrks.rpy", line 83, in <module>
    texteSoin = blessures_.SoignerBlessure(blessureK, situation_)
NameError: global name 'blessureK' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/extremis/coteries/orks/evts_RejOrks.rpy", line 77, in script
    python:
  File "renpy/ast.py", line 922, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2218, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/extremis/coteries/orks/evts_RejOrks.rpy", line 83, in <module>
    texteSoin = blessures_.SoignerBlessure(blessureK, situation_)
  File "extremis/humanite/sante/pbsante.py", line 274, in SoignerBlessure
NameError: global name 'blessureK' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
DestinExtremis 1.0
Sun Jun  6 00:18:58 2021
